import { TTSVoice } from './types';

// New: Niche Options for tailored AI prompting (RESTRUCTURED AND EXPANDED)
export const nicheOptions = [
    { value: "", label: "-- Select a Project Niche --" },
    { value: "Default / General", label: "Default / General (If you cannot find the right niche)", isNew: true },
    
    // --- Factual & Documentary ---
    { value: "3DMythBustingExplainer", label: "3D Explainer & Myth Busting (Facts)", isNew: true },
    
    // --- Religious & Spiritual ---
    
    // --- Calming & Storytelling ---
    
    // --- Sci-Fi & Animation ---
    
    // --- New Niches ---
    { value: "StylizedMatteHistory", label: "Stylized 3D History & Legends", isNew: true },
    { value: "HistoricalStickfigureExplainer", label: "Historical Stick Figure Animation Explainer", isNew: true },
    { value: "CocomelonKidsRhyme", label: "3D Kids Rhyme (Cocomelon Style) (No Voice)", isNew: true },
    { value: "MeditativeEpicHistory", label: "Meditative Cinematic History", isNew: true },
    { value: "IslamicHistory", label: "Islamic / Religious History", isNew: true },
    { value: "2DIslamicMoralStory", label: "2D Islamic Moral Story (Animated)", isNew: true },
    { value: "BengaliRuralHorror2D", label: "2D Bengali Horror Cartoon (Bhuter Golpo)", isNew: true },
    { value: "CinematicEpicHistory", label: "Cinematic Epic History Documentary", isNew: true },
    { value: "CinematicScienceDoc", label: "Premium Science Documentary", isNew: true },
    { value: "BackyardBugMyths", label: "Nature & Bug Myths Documentary", isNew: true },
    { value: "PrehistoricDocumentary", label: "Cinematic Prehistory", isNew: true },
    { value: "HyperRealWildlifeSurvival", label: "Hyper-Realistic Wildlife Drama (No Voiceover)", isNew: true },
    { value: "HistoricalAISurvival", label: "Historical Survival Reconstruction", isNew: true },
    { value: "DeepSeaDocumentary", label: "Cinematic Deep Sea Documentary", isNew: true },
    { value: "SleepHistoryStory", label: "History Sleep Stories", isNew: true },
    { value: "WildlifeBirdDoc", label: "Avian Wildlife Documentary", isNew: true },
    { value: "SatisfyingCraftASMR", label: "Satisfying DIY & Resin Art (No Voiceover)", isNew: true },
    { value: "DarkMaritimeHistory", label: "Dark Maritime Mythology", isNew: true },
    { value: "CinematicWildlifeDoc", label: "Epic Nature Documentary", isNew: true },
    { value: "3DAnatomyDigestion", label: "3D Anatomy & Food Science", isNew: true },
    { value: "CinematicFoodHistory", label: "Cinematic Food History Documentary", isNew: true },
    { value: "CinematicCityReconstruction", label: "Cinematic City Reconstruction Documentary", isNew: true },
    { value: "AnthropomorphicCatComedy", label: "AI Cat Funny Moment (No Voice)", isNew: true },
    { value: "3DAnimalRescue", label: "3D Animal Rescue (Kids Cartoon)", isNew: true },
    { value: "DangerousOceansDocumentary", label: "Dangerous Oceans Documentary", isNew: true },
    { value: "CinematicEarth", label: "Cinematic Dark Documentary (Earth & Evolution)", isNew: true },
    { value: "CityEvolutionTimelapse", label: "City Evolution Timelapse (No Voice)", isNew: true },
    { value: "FootballTactics", label: "Football Tactics Analysis", isNew: true },
    { value: "GeoDocumentaryLifestyle", label: "Travel Lifestyle Documentary", isNew: true },
    { value: "GunExperiments", label: "Gun Test and Experiment", isNew: true },
    { value: "PaintMixingASMR", label: "Handcraft Paint Mix (No Voice)", isNew: true },
    { value: "FoundFootageMythos", label: "Found Footage Horror POV (Sudden Attack)", isNew: true },
    { value: "CyberpunkMiniatureMacro", label: "Cyberpunk Figure Showcase (No Voice)", isNew: true },
    { value: "GhibliSurvivalAnime", label: "2D Anime Survival (Ghibli Style) (No Voice)", isNew: true },
];

// স্টাইল এবং থিমের তালিকা (Massively Expanded for YouTube Automation)
export const themeOptions = [
    "Action",
    "Adventure",
    "AI & Robotics",
    "Anatomy",
    "Ancient Civilization",
    "Ancient History",
    "Anime",
    "Animation",
    "Aquarium",
    "Art",
    "ASMR",
    "Astronomy",
    "Aviation",
    "Baking",
    "Basketball",
    "Beauty",
    "Bedtime Story",
    "Biblical",
    "Bikes",
    "Biography",
    "Biology",
    "Bodybuilding",
    "Boxing",
    "Buddhism",
    "Business",
    "Cars",
    "Cartoon",
    "Cats",
    "CCTV",
    "Chemistry",
    "Cinematic",
    "Coding",
    "Comedy",
    "Cooking",
    "Corporate",
    "Cosmos",
    "Crafts",
    "Creepypasta",
    "Cricket",
    "Crime Story",
    "Crypto",
    "Cultural",
    "Cyberpunk",
    "Desert",
    "Detective",
    "DIY",
    "Documentary",
    "Dogs",
    "Drama",
    "Drone Footage",
    "Economics",
    "Educational",
    "Educational (Kids)",
    "Entrepreneurship",
    "Esports",
    "Espionage",
    "Extreme Sports",
    "Fairy Tale",
    "Fantasy",
    "Fashion",
    "Finance",
    "Fitness",
    "Folklore",
    "Food",
    "Football",
    "Forest",
    "Found Footage",
    "Futurism",
    "Gaming",
    "Gardening",
    "Gadgets",
    "Geography",
    "Geopolitics",
    "Ghost Story",
    "Hacking",
    "Health & Wellness",
    "Hinduism",
    "History",
    "Home Decor",
    "Horror",
    "Interior Design",
    "Interview",
    "Islamic",
    "Jungle",
    "Kids Story",
    "Life Hacks",
    "Lifestyle",
    "Luxury",
    "Makeup",
    "Maps",
    "Marine Life",
    "Marketing",
    "Medical",
    "Meditation",
    "Medieval",
    "Mental Health",
    "Metaverse",
    "Military",
    "MMA",
    "Money",
    "Mountains",
    "Mystery",
    "Mythology",
    "Nature",
    "News Report",
    "Nursery Rhyme",
    "Nutrition",
    "Ocean",
    "Pets",
    "Philosophy",
    "Physics",
    "Podcast Visualization",
    "Pottery",
    "Psychology",
    "Puppet Show",
    "Quranic",
    "Racing",
    "Real Estate",
    "Real Footage",
    "Realistic",
    "Religious",
    "Romance",
    "Sci-Fi",
    "Science",
    "Ships",
    "Sitcom",
    "Sleep Aid",
    "Space",
    "Spiritual",
    "Sports",
    "Stock Market",
    "Street Food",
    "Superhero",
    "Supercars",
    "Talk Show",
    "Tech Review",
    "Technology",
    "Thriller",
    "Toy Review",
    "Trains",
    "Travel",
    "Tribal",
    "True Crime",
    "Vlog",
    "War",
    "Wellness",
    "Wildlife",
    "Woodworking",
    "Yoga",
    "Narrative",
    "3D Animation",
    "Explainer",
    "Science & Experiment",
    "Human Interest",
    "Religion",
    "Magic",
    "Relaxation",
    "Crime",
    "Dystopian",
    "Kids Cartoon",
    "Survival",
    "Dark Nature",
    "Evolution",
    "Timelapse",
    "Architecture",
    "Tactical Analysis",
    "Satisfying",
    "Historical",
    "Animal Behavior",
    "Meme",
    "Paranormal",
    "Miniature",
];

export const styleModifiers = [
    "16-bit",
    "1940s Film Grain",
    "2D Vector Art",
    "3D Render",
    "4K",
    "8-bit",
    "8K",
    "Abstract",
    "Acrylic",
    "Aged Paper Texture",
    "Analog Video Signal",
    "Anime",
    "Art Deco",
    "Baroque",
    "Black and White",
    "Blender",
    "Blueprint",
    "Blue Hour",
    "Bokeh",
    "CCTV Grain",
    "CGI",
    "Cel Shaded",
    "Charcoal Sketch",
    "Cinematic Lighting",
    "Claymation",
    "Comic Book",
    "Corporate Memphis",
    "Cubism",
    "Cyberpunk Neon",
    "Damaged Film",
    "Dashcam",
    "Depth of Field",
    "Dieselpunk",
    "Disney Style",
    "Double Exposure",
    "Dramatic Lighting",
    "Dreamworks Style",
    "Drone Shot",
    "Fisheye Lens",
    "Flat Design",
    "Glitch Art",
    "Golden Hour",
    "GoPro Footage",
    "Gothic",
    "Graffiti",
    "Graphic Novel",
    "Grayscale",
    "HDR",
    "High Poly",
    "Historical Archives Tone",
    "Holographic",
    "Glassmorphism",
    "Impressionist",
    "Infographic",
    "Ink Illustration",
    "Isometric",
    "Kodachrome Colors",
    "Line Art",
    "Long Exposure",
    "Low Poly",
    "Macro Lens",
    "Manga Style",
    "Minimalist",
    "Minecraft Style",
    "Monochrome",
    "Motion Blur",
    "Night Vision",
    "Noir",
    "Octane Render",
    "Oil Painting",
    "Old Newsreel",
    "Origami",
    "Paper Cutout",
    "Pastel",
    "Pencil Drawing",
    "Photorealistic",
    "Pixar Style",
    "Pixel Art",
    "Polaroid Effect",
    "Pop Art",
    "Psychedelic",
    "Puppetry",
    "Renaissance",
    "Retro",
    "Retro Gaming",
    "Roblox Style",
    "Sepia Tone",
    "Silent Movie Style",
    "Soft Focus",
    "Steampunk",
    "Stipple",
    "Stop Motion",
    "Street Art",
    "Studio Ghibli",
    "Studio Light",
    "Surreal",
    "Synthwave",
    "Telephoto Lens",
    "Thermal Vision",
    "Toon Realism",
    "Ukiyo-e",
    "Unreal Engine 5",
    "Vaporwave",
    "Vintage",
    "Voxel Art",
    "Watercolor",
    "Whiteboard Animation",
    "Wide Angle",
    "Wireframe",
    "WW2 Documentary Look",
    "X-Ray",
    "8K Resolution",
    "Volumetric Lighting",
    "Shot on 35mm lens",
    "Ray Tracing",
    "Subsurface Scattering",
    "Vibrant Colors",
    "Studio Lighting",
    "Hyper-realistic",
    "Macro Detail",
    "Sharp Focus",
    "Documentary Photography",
    "1940s Vintage Look",
    "Film Grain",
    "Archival Footage",
    "Damaged Newsreel",
    "High Contrast",
    "Netflix Documentary Style",
    "Natural Lighting",
    "Shallow Depth of Field",
    "Cinematic Color Grading",
    "National Geographic Style",
    "Ultra-realistic 4K",
    "Macro Photography",
    "Epic Scale",
    "Golden Hour Lighting",
    "Highly Detailed Architecture",
    "Cinematic Haze",
    "Ethereal",
    "Bioluminescence",
    "Soft Dreamy Lighting",
    "Pastel Colors",
    "Fairy Tale Aesthetic",
    "Warm Golden Light",
    "Cinematic Landscape",
    "Ultra-detailed Nature",
    "Gritty Texture",
    "Chiaroscuro Lighting",
    "Moody Vibe",
    "Desaturated",
    "Dark Fantasy",
    "Foggy Atmosphere",
    "Moody Color Palette",
    "Volumetric Neon Lighting",
    "Cyberpunk Aesthetic",
    "James Webb Telescope Style",
    "Photorealistic 8K",
    "Glowing Nebulas",
    "Deep Black Space",
    "Studio Ghibli Aesthetic",
    "Hand-drawn",
    "Painterly Backgrounds",
    "Cel-shaded",
    "Warm Natural Light",
    "Pixar 3D Style",
    "Soft Global Illumination",
    "Hyper-realistic Marine Footage",
    "Stormy Atmosphere",
    "Volumetric Fog",
    "Macro Details",
    "Hyper-realistic 3D",
    "Day-Night Cycle",
    "High-Definition Texture",
    "Realistic Match Footage",
    "Broadcast Quality",
    "Stadium Floodlights",
    "Technical Overlay",
    "4K Drone Footage",
    "Vibrant Natural Light",
    "BBC Style",
    "High-speed Photography",
    "Slow Motion",
    "Cinematic Action",
    "Ultra-realistic 8K",
    "Outdoor Daylight",
    "Macro Videography",
    "Soft Diffused Lighting",
    "Glossy Reflection",
    "Pearlescent Texture",
    "Museum-quality Oil Painting",
    "Cinematic Candlelight",
    "Hyper-realistic 8K",
    "Hyper-realistic AI Reconstruction",
    "Hyper-realistic Live Action",
    "4K Smartphone Recording",
    "Screen Glow Lighting",
    "Raw Handheld Style",
    "Photorealistic Fur",
    "Raw-recording Style",
    "Hyper-realistic VFX",
    "VHS Glitch",
    "Gloomy Low Light",
    "Soft Spotlights",
    "Photorealistic Texture",
    "Hyper-detailed Plastic",
    "Warm God Rays",
    "High-quality 2D Animation",
];

export const cameraAngles = [
    { value: "Arc Shot", description: "Camera circles around the subject." },
    { value: "Bird's Eye View", description: "Directly overhead shot." },
    { value: "Body Cam (POV)", description: "Realistic, shaky chest-mounted camera view." },
    { value: "Bullet Time", description: "Time freezes/slows while camera moves around." },
    { value: "Cinematic", description: "High production value composition and movement." },
    { value: "Close-up", description: "Tightly frames a person or object to show detail or emotion." },
    { value: "Crane Shot", description: "Camera moves vertically high up or down." },
    { value: "Crash Zoom", description: "Rapid, dramatic zoom into a subject." },
    { value: "Dolly Zoom", description: "Vertigo effect: camera moves back while zooming in." },
    { value: "Drone Shot", description: "Aerial footage, smooth and sweeping." },
    { value: "Dutch Angle", description: "Tilted camera angle to create unease or tension." },
    { value: "Dynamic Camera", description: "Active, moving camera that follows the action energetically." },
    { value: "Establishing Shot", description: "Sets up the context for a scene, often a building or landscape." },
    { value: "Extreme Close-up", description: "Focuses on a tiny detail like an eye or a ring." },
    { value: "Extreme Wide Shot", description: "Shows the subject from a great distance, emphasizing the location." },
    { value: "Fisheye", description: "Ultra-wide distorted perspective." },
    { value: "Full Shot", description: "Shows the character from head to toe." },
    { value: "Gimbal Shot", description: "Perfectly smooth, flowing camera movement." },
    { value: "Handheld", description: "Shaky, realistic feel like a documentary or horror." },
    { value: "High Angle", description: "Camera looks down, making the subject look vulnerable." },
    { value: "Low Angle", description: "Camera looks up at the subject, making them look powerful." },
    { value: "Macro", description: "Extreme magnification for small objects." },
    { value: "Medium Close-up", description: "Frames the subject from chest up." },
    { value: "Medium Shot", description: "Shows the subject from the waist up. Good for dialogue." },
    { value: "Over-the-Shoulder", description: "Shot from behind a character, looking at the subject." },
    { value: "Pan Shot", description: "Camera rotates horizontally." },
    { value: "Point of View (POV)", description: "Shows exactly what a character is seeing." },
    { value: "Rack Focus", description: "Focus shifts from one object to another." },
    { value: "Steadicam", description: "Smooth, floating camera movement following action." },
    { value: "Tilt Shot", description: "Camera rotates vertically." },
    { value: "Tracking Shot", description: "Camera moves alongside the subject." },
    { value: "Wide Shot", description: "Shows the entire subject and the environment." },
    { value: "Worm's Eye View", description: "Looking up from the ground level." },
    { value: "Zoom In", description: "Lens focal length changes to get closer." },
    { value: "Zoom Out", description: "Lens focal length changes to get further." },
    { value: "Eye-level", description: "Niche specific angle" },
    { value: "Cinematic Pan", description: "Niche specific angle" },
    { value: "Dynamic Zoom", description: "Niche specific angle" },
    { value: "Fast Pan", description: "Niche specific angle" },
    { value: "Wide Angle", description: "Niche specific angle" },
    { value: "Handheld Shaky Cam", description: "Niche specific angle" },
    { value: "Stable Gimbal Shot", description: "Niche specific angle" },
    { value: "Slow Pan", description: "Niche specific angle" },
    { value: "Static Shot", description: "Niche specific angle" },
    { value: "Slow Drone Drift", description: "Niche specific angle" },
    { value: "Slow Push-in", description: "Niche specific angle" },
    { value: "Slow Orbit", description: "Niche specific angle" },
    { value: "Dynamic Shot", description: "Niche specific angle" },
    { value: "Fixed-Camera", description: "Niche specific angle" },
    { value: "Wide-angle Overview", description: "Niche specific angle" },
    { value: "Macro View", description: "Niche specific angle" },
    { value: "Slow Motion", description: "Niche specific angle" },
    { value: "Static Portrait", description: "Niche specific angle" },
    { value: "First-person POV", description: "Niche specific angle" },
    { value: "Static Mid-shot", description: "Niche specific angle" },
    { value: "Panic Zoom", description: "Niche specific angle" },
    { value: "Macro Pan", description: "Niche specific angle" },
    { value: "Slow Tilt-up", description: "Niche specific angle" },
    { value: "Gentle Tracking", description: "Niche specific angle" },
];

// Expanded Tones List based on user input
export const ttsTones = [
    'All Tones',
    'Male',
    'Female',
    'Old',
    'Young',
    'Middle-Aged',
    'Ancient',
    'Ancient Wisdom',
    'Angry',
    'ASMR',
    'Audiobook Reading',
    'Biographical',
    'Casual',
    'Character Voice',
    'Cheerful',
    'Comedy Skit',
    'Conversational',
    'Corporate Narration',
    'Crime Story',
    'Documentary',
    'Dynamic',
    'Educational',
    'E-Learning Module',
    'Fact',
    'Fantasy Epic',
    'Financial Advice',
    'Formal',
    'Geography Documentary',
    'Guided Meditation',
    'Happy',
    'Health & Fitness',
    'History',
    'Horror Story',
    'Inspirational',
    'Islamic History',
    'Kids Bedtime Story',
    'Medical Narration',
    'Medieval History',
    'Motivational',
    'Movie Trailer',
    'Mysterious',
    'Mythology',
    'Nature/Geography',
    'Neutral',
    'News Report',
    'Odd Story',
    'Podcast Intro',
    'Political Commentary',
    'Product Demo',
    'Sad',
    'Sci-Fi Narration',
    'Scientific Narration',
    'Sleep Story',
    'Sleeping Story',
    'Space Documentary',
    'Suspenseful',
    'Taunting',
    'Tech Review',
    'Whisper ASMR',
    'Excited', 
    'Annoyed', 'Anxious', 'Apologetic', 'Argumentative', 'Assertive', 'Authoritative',
    'Calm', 'Caring', 'Confident', 'Concerned', 'Contemplative', 'Content',
    'Curious', 'Defensive', 'Depressed', 'Disappointed', 'Disgusted', 'Dramatic',
    'Dreamy', 'Empathetic', 'Encouraging', 'Enthusiastic', 'Fearful', 'Friendly',
    'Gentle', 'Grateful', 'Hopeful', 'Humorous', 'Informative', 
    'Joyful', 'Loving', 'Melancholy', 'Narrating', 'Nostalgic',
    'Objective', 'Optimistic', 'Passionate', 'Pessimistic', 'Playful', 'Pleading',
    'Proud', 'Regretful', 'Relieved', 'Sarcastic', 'Serious', 'Shouting',
    'Shy', 'Sincere', 'Somber', 'Soothing', 'Stressed', 'Surprised',
    'Sympathetic', 'Thoughtful', 'Tired', 'Worried'
];

// --- COMPLETE VOICE LIST ---
export const ttsVoices: TTSVoice[] = [
    // --- BENGALI VOICES ---
    { conceptualName: 'নবনীতা (Female)', apiName: 'bn-IN-Standard-A', gender: 'Female', category: 'Narrator', language: 'Bengali', tones: ['Neutral', 'Formal', 'Audiobook Reading', 'News Report'], color: '#FF69B4', use_case: 'A clear, professional female voice for Bengali narration and news.' },
    { conceptualName: 'অর্ণব (Male)', apiName: 'bn-IN-Standard-B', gender: 'Male', category: 'Narrator', language: 'Bengali', tones: ['Neutral', 'Formal', 'Documentary', 'Storytelling'], color: '#1E90FF', use_case: 'A standard, clear male voice for Bengali documentaries and formal content.' },
    { conceptualName: 'ঈশিতা (Female)', apiName: 'bn-IN-Standard-C', gender: 'Female', category: 'Conversational', language: 'Bengali', tones: ['Conversational', 'Casual', 'Cheerful', 'Friendly'], color: '#FF69B4', use_case: 'A friendly and conversational female voice for modern Bengali content.' },
    { conceptualName: 'আকাশ (Male)', apiName: 'bn-IN-Standard-D', gender: 'Male', category: 'Deep', language: 'Bengali', tones: ['Deep', 'Storytelling', 'Sad', 'Audiobook Reading'], color: '#1E90FF', use_case: 'A deep and resonant male voice for Bengali storytelling and audiobooks.' },

    // === CORE VOICES (CONCEPTUAL) ===
    { conceptualName: 'Kore (Standard Female)', apiName: 'Kore', gender: 'Female', category: 'Neutral', language: 'English', tones: ['Neutral', 'Documentary', 'Fact', 'History', 'Educational', 'News Report', 'Corporate Narration', 'Formal', 'Middle-Aged'], color: '#FF69B4', use_case: 'A firm, clear female voice. Ideal for professional presentations, news, and factual content.' },
    { conceptualName: 'Leda (Youthful Female)', apiName: 'Zephyr', gender: 'Female', category: 'Cheerful', language: 'English', tones: ['Cheerful', 'Happy', 'Dynamic', 'Motivational', 'Comedy Skit', 'Product Demo', 'Inspirational', 'Young'], color: '#FF69B4', use_case: 'A youthful, higher-pitched female voice perfect for energetic, bright, and cheerful content.' },
    { conceptualName: 'Archenor (Deep Male)', apiName: 'Puck', gender: 'Male', category: 'History', language: 'English', tones: ['History', 'Ancient', 'Horror Story', 'Crime Story', 'Documentary', 'Medieval History', 'Fantasy Epic', 'Sci-Fi Narration', 'Middle-Aged'], color: '#1E90FF', use_case: 'A deep, resonant male voice perfect for epic stories, trailers, and serious documentaries.' },
    { conceptualName: 'Pulcherrima (Calm Male)', apiName: 'Charon', gender: 'Male', category: 'Sleeping Story', language: 'English', tones: ['Sleeping Story', 'Kids Bedtime Story', 'Sad', 'ASMR', 'Nature/Geography', 'Sleep Story', 'Guided Meditation', 'Young'], color: '#1E90FF', use_case: 'A calm and soothing male voice, ideal for bedtime stories, meditation, and gentle narration.' },
    { conceptualName: 'Enceladus (Crisp Male)', apiName: 'Fenrir', gender: 'Male', category: 'Horror Story', language: 'English', tones: ['Horror Story', 'Crime Story', 'Odd Story', 'ASMR', 'Taunting', 'Mysterious', 'Suspenseful', 'Middle-Aged'], color: '#1E90FF', use_case: 'A crisp, sharp male voice for mysteries, suspense, horror, or content requiring an edge.' },

    // === SPECIALIZED CHARACTER VOICES (CONCEPTUAL) ===
    { conceptualName: 'Eldred (The Storyteller)', apiName: 'Charon', gender: 'Male', category: 'Old', language: 'English', tones: ['Old', 'Ancient Wisdom', 'Storytelling', 'History', 'Sad', 'Kids Bedtime Story'], color: '#1E90FF', use_case: 'A very deep and wise male voice. Sounds like an old grandfather telling stories by a fire.' },
    { conceptualName: 'Hesta (Grandmother)', apiName: 'Kore', gender: 'Female', category: 'Old', language: 'English', tones: ['Old', 'Ancient Wisdom', 'Character Voice', 'Fantasy Epic', 'Storytelling'], color: '#FF69B4', use_case: 'A warm, slightly creaky, and kind older female voice. Perfect for grandmotherly advice or witch characters.' },
    { conceptualName: 'Thaddeus (The Professor)', apiName: 'Puck', gender: 'Male', category: 'Old', language: 'English', tones: ['Old', 'Educational', 'History', 'Scientific Narration', 'Biographical', 'Formal'], color: '#1E90FF', use_case: 'An intellectual, aged male voice. Sounds like a senior professor giving a lecture or reading a diary.' },
    { conceptualName: 'Agatha (Mystery)', apiName: 'Kore', gender: 'Female', category: 'Old', language: 'English', tones: ['Old', 'Mysterious', 'Horror Story', 'Crime Story', 'Character Voice'], color: '#FF69B4', use_case: 'A sharp, aged female voice with a mysterious edge. Great for horror, mystery, or strict characters.' },
    { conceptualName: 'Gacrux (Cosmic Narrator)', apiName: 'Puck', gender: 'Male', category: 'Space Documentary', language: 'English', tones: ['Space Documentary', 'History', 'Documentary', 'Sci-Fi Narration', 'Ancient Wisdom', 'Formal', 'Fact', 'Middle-Aged'], color: '#1E90FF', use_case: 'A deep, commanding, and resonant voice perfect for space, history, and grand-scale documentaries.' },
    { conceptualName: 'Chronicler', apiName: 'Puck', gender: 'Male', category: 'History', language: 'English', tones: ['History', 'Documentary', 'Ancient', 'Medieval History', 'Fact', 'Fantasy Epic', 'Biographical', 'Islamic History', 'Old'], color: '#1E90FF', use_case: 'A mature, authoritative male voice with gravitas, as if recounting epic tales from a forgotten age.' },
    { conceptualName: 'Clio', apiName: 'Kore', gender: 'Female', category: 'History', language: 'English', tones: ['History', 'Ancient Wisdom', 'Documentary', 'Fact', 'Sad', 'Biographical', 'Formal', 'Old'], color: '#FF69B4', use_case: 'A mature, wise female voice, conveying decades of knowledge. Perfect for historical narratives and biographies.' },
    { conceptualName: 'Newton', apiName: 'Charon', gender: 'Male', category: 'Scientific Narration', language: 'English', tones: ['Scientific Narration', 'Educational', 'Fact', 'Biographical', 'History', 'Middle-Aged'], color: '#1E90FF', use_case: 'A clear, intellectual, and slightly aged voice, perfect for scientific explanations and biographies.' },
    { conceptualName: 'Cleopatra', apiName: 'Kore', gender: 'Female', category: 'History', language: 'English', tones: ['History', 'Ancient', 'Biographical', 'Formal', 'Political Commentary', 'Middle-Aged'], color: '#FF69B4', use_case: 'A regal, commanding, and articulate female voice for powerful historical figures.' },
    { conceptualName: 'Herodotus', apiName: 'Puck', gender: 'Male', category: 'History', language: 'English', tones: ['History', 'Documentary', 'Ancient', 'Medieval History', 'Biographical', 'Audiobook Reading', 'Old'], color: '#1E90FF', use_case: 'A classic, trustworthy narrator for historical accounts and epic chronicles.' },
    { conceptualName: 'Churchill', apiName: 'Puck', gender: 'Male', category: 'Political Commentary', language: 'English', tones: ['Political Commentary', 'History', 'Formal', 'Biographical', 'Documentary', 'Old'], color: '#1E90FF', use_case: 'An authoritative, formal, and resonant voice suitable for political and historical commentary.' },
    { conceptualName: 'Archivist', apiName: 'Charon', gender: 'Male', category: 'Ancient Wisdom', language: 'English', tones: ['Ancient Wisdom', 'History', 'Documentary', 'Fact', 'Audiobook Reading', 'Sad', 'Medieval History', 'Old'], color: '#1E90FF', use_case: 'An old, slightly frail but clear male voice, as if reading from a dusty historical tome.' },
    { conceptualName: 'Saga', apiName: 'Kore', gender: 'Female', category: 'History', language: 'English', tones: ['History', 'Audiobook Reading', 'Documentary', 'Ancient Wisdom', 'Formal', 'Neutral', 'Middle-Aged'], color: '#FF69B4', use_case: 'A calm, steady, and engaging voice for narrating long historical sagas and audiobooks.' },
    { conceptualName: 'Lovecraft', apiName: 'Fenrir', gender: 'Male', category: 'Horror Story', language: 'English', tones: ['Horror Story', 'Mysterious', 'Suspenseful', 'Odd Story', 'Ancient', 'Fantasy Epic', 'Middle-Aged'], color: '#1E90FF', use_case: 'A deep, unsettling, and atmospheric voice for cosmic horror, mysteries, and suspenseful tales.' },
    { conceptualName: 'Investigator', apiName: 'Puck', gender: 'Male', category: 'Crime Story', language: 'English', tones: ['Crime Story', 'Suspenseful', 'Documentary', 'Fact', 'Formal', 'Middle-Aged'], color: '#1E90FF', use_case: 'A calm, methodical, and serious voice, perfect for narrating true crime documentaries.' },
    { conceptualName: 'Noir (Detective)', apiName: 'Fenrir', gender: 'Male', category: 'Character Voice', language: 'English', tones: ['Character Voice', 'Crime Story', 'Suspenseful', 'Mysterious', 'Audiobook Reading', 'Middle-Aged'], color: '#1E90FF', use_case: 'A gritty, low, and slightly cynical voice. Perfect for detective stories and noir-style narration.' },
    { conceptualName: 'Explorer', apiName: 'Puck', gender: 'Male', category: 'Geography Documentary', language: 'English', tones: ['Geography Documentary', 'Nature/Geography', 'Documentary', 'Inspirational', 'Young'], color: '#1E90FF', use_case: 'An adventurous, clear, and engaging voice for geography, nature, and exploration documentaries.' },
    { conceptualName: 'Atlas', apiName: 'Puck', gender: 'Male', category: 'Geography Documentary', language: 'English', tones: ['Geography Documentary', 'Nature/Geography', 'Documentary', 'Ancient', 'Sci-Fi Narration', 'Middle-Aged'], color: '#1E90FF', use_case: 'A grand, deep voice for geography documentaries and nature exploration shows.' },
    { conceptualName: 'Physician', apiName: 'Kore', gender: 'Female', category: 'Medical Narration', language: 'English', tones: ['Medical Narration', 'Health & Fitness', 'Fact', 'Educational', 'E-Learning Module', 'Formal', 'Middle-Aged'], color: '#FF69B4', use_case: 'A calm, reassuring, and authoritative voice for medical advice and health-related content.' },
    { conceptualName: 'Coach', apiName: 'Fenrir', gender: 'Male', category: 'Health & Fitness', language: 'English', tones: ['Health & Fitness', 'Motivational', 'Dynamic', 'Inspirational', 'Angry', 'Young'], color: '#1E90FF', use_case: 'An energetic, powerful, and motivating voice, perfect for gym instructions and fitness content.' },
    { conceptualName: 'Aura', apiName: 'Zephyr', gender: 'Female', category: 'Guided Meditation', language: 'English', tones: ['Guided Meditation', 'Sleep Story', 'ASMR', 'Sleeping Story', 'Whisper ASMR', 'Happy', 'Kids Bedtime Story', 'Young'], color: '#FF69B4', use_case: 'A youthful and serene voice, perfect for guided meditations, affirmations, and gentle sleep stories.' },
    { conceptualName: 'Morpheus', apiName: 'Charon', gender: 'Male', category: 'Sleep Story', language: 'English', tones: ['Sleep Story', 'Sleeping Story', 'ASMR', 'Sad', 'Guided Meditation', 'Whisper ASMR', 'Middle-Aged'], color: '#1E90FF', use_case: 'A deep, hypnotic voice designed to lull listeners to sleep.' },
    { conceptualName: 'Valkyrie', apiName: 'Kore', gender: 'Female', category: 'Fantasy Epic', language: 'English', tones: ['Fantasy Epic', 'Mythology', 'Dynamic', 'History', 'Ancient', 'Young'], color: '#FF69B4', use_case: 'A strong, epic, and resonant female voice for fantasy tales, mythology, and heroic sagas.' },
    { conceptualName: 'Goliath', apiName: 'Fenrir', gender: 'Male', category: 'Fantasy Epic', language: 'English', tones: ['Fantasy Epic', 'Angry', 'Ancient', 'Horror Story', 'Taunting', 'Middle-Aged'], color: '#1E90FF', use_case: 'A deep, booming, and powerful male voice, suitable for villains, monsters, or epic pronouncements.' },
    { conceptualName: 'Siren', apiName: 'Zephyr', gender: 'Female', category: 'Fantasy Epic', language: 'English', tones: ['Fantasy Epic', 'Mysterious', 'Mythology', 'Sleeping Story', 'Whisper ASMR', 'Young'], color: '#FF69B4', use_case: 'An alluring, mysterious, and slightly ethereal voice for fantasy, mythology, or seductive characters.' },
    { conceptualName: 'Da Vinci', apiName: 'Charon', gender: 'Male', category: 'Ancient Wisdom', language: 'English', tones: ['Ancient Wisdom', 'Biographical', 'Educational', 'History', 'Fact', 'Old'], color: '#1E90FF', use_case: 'A wise, artistic, and thoughtful aged voice, embodying creativity and intellect.' },
    { conceptualName: 'Maverick (Movie Trailer)', apiName: 'Fenrir', gender: 'Male', category: 'Character Voice', language: 'English', tones: ['Character Voice', 'Movie Trailer', 'Dynamic', 'Inspirational', 'Angry', 'Young'], color: '#1E90FF', use_case: 'An energetic, deep, and impactful voice perfect for movie trailers and promotional content.' },
    { conceptualName: 'Scribe (Tech Reviewer)', apiName: 'Charon', gender: 'Male', category: 'Character Voice', language: 'English', tones: ['Character Voice', 'Tech Review', 'Conversational', 'Casual', 'Podcast Intro', 'Educational', 'Young'], color: '#1E90FF', use_case: 'A clear, friendly, and conversational voice. Perfect for tech reviews, tutorials, and explainers.' },
    { conceptualName: 'Oracle', apiName: 'Kore', gender: 'Female', category: 'Financial Advice', language: 'English', tones: ['Financial Advice', 'Fact', 'Tech Review', 'Neutral', 'Corporate Narration', 'Political Commentary', 'Middle-Aged'], color: '#FF69B4', use_case: 'A confident, articulate voice for financial news, market analysis, and expert advice.' },
    { conceptualName: 'Sage', apiName: 'Kore', gender: 'Female', category: 'Ancient Wisdom', language: 'English', tones: ['Ancient Wisdom', 'Sad', 'Sleeping Story', 'Sleep Story', 'Audiobook Reading', 'Inspirational', 'Old'], color: '#FF69B4', use_case: 'A gentle, older female voice, conveying wisdom and experience. Ideal for life advice and storytelling.' },
    { conceptualName: 'Mad Scientist', apiName: 'Fenrir', gender: 'Male', category: 'Comedy Skit', language: 'English', tones: ['Comedy Skit', 'Odd Story', 'Dynamic', 'Sci-Fi Narration', 'Character Voice', 'Middle-Aged'], color: '#1E90FF', use_case: 'An eccentric, energetic, and slightly unhinged voice, great for comedy or quirky explainers.' },
    { conceptualName: 'Erinome (Informative)', apiName: 'Kore', gender: 'Female', category: 'Fact', language: 'English', tones: ['Fact', 'Documentary', 'Neutral', 'Educational', 'E-Learning Module', 'News Report', 'Middle-Aged'], color: '#FF69B4', use_case: 'A clear, middle-pitch female voice for informative and straightforward content.' },
    { conceptualName: 'Oran', apiName: 'Puck', gender: 'Male', category: 'Documentary', language: 'English', tones: ['Documentary', 'Fact', 'History', 'Neutral', 'Tech Review', 'Political Commentary', 'Formal', 'Middle-Aged'], color: '#1E90FF', use_case: 'A firm, lower-middle pitch male voice for authoritative and serious content.' },
    { conceptualName: 'Umbriel', apiName: 'Fenrir', gender: 'Male', category: 'Nature/Geography', language: 'English', tones: ['Nature/Geography', 'Odd Story', 'Angry', 'Taunting', 'Comedy Skit', 'Casual', 'Conversational', 'Young'], color: '#1E90FF', use_case: 'A very deep, lower male pitch voice for casual and relaxed content.' },
    { conceptualName: 'Cygnus', apiName: 'Charon', gender: 'Male', category: 'Happy', language: 'English', tones: ['Happy', 'Cheerful', 'Motivational', 'Kids Bedtime Story', 'Inspirational', 'Podcast Intro', 'Young'], color: '#1E90FF', use_case: 'A warm and friendly male voice, perfect for storytelling and commercials.' },
    { conceptualName: 'Lyra', apiName: 'Zephyr', gender: 'Female', category: 'Kids Bedtime Story', language: 'English', tones: ['Kids Bedtime Story', 'Happy', 'Cheerful', 'Sleeping Story', 'Sleep Story', 'Casual', 'Young'], color: '#FF69B4', use_case: 'A sweet and gentle female voice, great for children\'s content and soft narration.' },
    { conceptualName: 'Zorp (Cartoon Alien)', apiName: 'Zephyr', gender: 'Female', category: 'Character Voice', language: 'English', tones: ['Character Voice', 'Comedy Skit', 'Sci-Fi Narration', 'Dynamic', 'Happy', 'Young'], color: '#FF69B4', use_case: 'A high-pitch, energetic, and quirky voice. Perfect for animated characters, aliens, or fun explainers.' },
    { conceptualName: 'Valor (Gentle Narrator)', apiName: 'Kore', gender: 'Female', category: 'Character Voice', language: 'English', tones: ['Character Voice', 'Audiobook Reading', 'Corporate Narration', 'Educational', 'Formal', 'Neutral', 'Middle-Aged'], color: '#FF69B4', use_case: 'A gentle, clear, and trustworthy voice. Ideal for professional narration, e-learning, and corporate content.' },
    { conceptualName: 'Odin (Mythic Storyteller)', apiName: 'Puck', gender: 'Male', category: 'Character Voice', language: 'English', tones: ['Character Voice', 'Mythology', 'Fantasy Epic', 'History', 'Ancient Wisdom', 'Documentary', 'Old'], color: '#1E90FF', use_case: 'A deep, powerful, and epic voice reminiscent of ancient gods and mythological tales.' },
    { conceptualName: 'Somnus (Sleepy Historian)', apiName: 'Charon', gender: 'Male', category: 'Character Voice', language: 'English', tones: ['Character Voice', 'Sleep Story', 'History', 'Ancient Wisdom', 'ASMR', 'Guided Meditation', 'Sleeping Story', 'Old'], color: '#1E90FF', use_case: 'A deep, and calming voice, specifically crafted for late-night history documentaries or sleep stories.' },

    // === API STANDARD VOICES ===
    { conceptualName: 'Achernar (API Standard)', apiName: 'Achernar', gender: 'Female', category: 'Corporate Narration', language: 'English', tones: ['Corporate Narration', 'E-Learning Module', 'Formal', 'Neutral'], color: '#FF69B4', use_case: 'A professional and direct female voice, excellent for corporate narration and e-learning modules.' },
    { conceptualName: 'Achird (API Standard)', apiName: 'Achird', gender: 'Male', category: 'Conversational', language: 'English', tones: ['Conversational', 'Podcast Intro', 'Casual', 'Friendly', 'Product Demo'], color: '#1E90FF', use_case: 'A friendly and warm male voice, perfect for conversational podcasts, commercials, and tutorials.' },
    
    // ALGENIB UPDATED TO OLD
    { conceptualName: 'Algenib (API Standard)', apiName: 'Algenib', gender: 'Male', category: 'Old', language: 'English', tones: ['Old', 'Documentary', 'News Report', 'Formal', 'Authoritative', 'Fact'], color: '#1E90FF', use_case: 'An authoritative and deep male voice, ideal for news reporting, documentaries, and formal announcements.' },
    
    // ALGIEBA UPDATED TO OLD
    { conceptualName: 'Algieba (API Standard)', apiName: 'Algieba', gender: 'Male', category: 'Old', language: 'English', tones: ['Old', 'Audiobook Reading', 'History', 'Biographical', 'Storytelling'], color: '#1E90FF', use_case: 'A mature and steady male voice, suitable for audiobooks and long-form historical narration.' },
    
    { conceptualName: 'Alnilam (API Standard)', apiName: 'Alnilam', gender: 'Male', category: 'Movie Trailer', language: 'English', tones: ['Movie Trailer', 'Motivational', 'Dynamic', 'Inspirational'], color: '#1E90FF', use_case: 'A strong, clear male voice, well-suited for impactful movie trailers and motivational content.' },
    { conceptualName: 'Aoede (API Standard)', apiName: 'Aoede', gender: 'Female', category: 'Cheerful', language: 'English', tones: ['Cheerful', 'Happy', 'Character Voice', 'Kids Bedtime Story'], color: '#FF69B4', use_case: 'A melodic and youthful female voice, great for cheerful storytelling, animations, and character work.' },
    { conceptualName: 'Autonoe (API Standard)', apiName: 'Autonoe', gender: 'Female', category: 'Guided Meditation', language: 'English', tones: ['Guided Meditation', 'ASMR', 'Sleep Story', 'Soothing'], color: '#FF69B4', use_case: 'A calm and gentle female voice, perfect for guided meditation, ASMR, and sleep stories.' },
    { conceptualName: 'Callirrhoe (API Standard)', apiName: 'Callirrhoe', gender: 'Female', category: 'Product Demo', language: 'English', tones: ['Product Demo', 'Corporate Narration', 'Formal', 'Elegant'], color: '#FF69B4', use_case: 'An elegant and articulate female voice, ideal for high-end product demos and sophisticated content.' },
    { conceptualName: 'Charon (API Standard)', apiName: 'Charon', gender: 'Male', category: 'Neutral', language: 'English', tones: ['Neutral', 'Educational', 'E-Learning Module', 'Informative'], color: '#1E90FF', use_case: 'A calm, standard male voice providing a neutral and clear tone for general-purpose narration.' },
    { conceptualName: 'Despina (API Standard)', apiName: 'Despina', gender: 'Female', category: 'Dynamic', language: 'English', tones: ['Dynamic', 'Cheerful', 'Product Demo', 'Conversational'], color: '#FF69B4', use_case: 'A crisp and engaging female voice, suitable for dynamic commercials and upbeat presentations.' },
    { conceptualName: 'Enceladus (API Standard)', apiName: 'Enceladus', gender: 'Male', category: 'Mysterious', language: 'English', tones: ['Mysterious', 'Suspenseful', 'Tech Review', 'Edgy'], color: '#1E90FF', use_case: 'A sharp, edgy male voice. The standard API version is great for content requiring an distinct, crisp tone.' },
    { conceptualName: 'Erinome (API Standard)', apiName: 'Erinome', gender: 'Female', category: 'Informative', language: 'English', tones: ['Informative', 'Educational', 'Neutral', 'Fact'], color: '#FF69B4', use_case: 'A clear, mid-range female voice for straightforward and informative content. A reliable choice for explainers.' },
    { conceptualName: 'Fenrir (API Standard)', apiName: 'Fenrir', gender: 'Male', category: 'Dramatic', language: 'English', tones: ['Dramatic', 'Angry', 'Taunting', 'Character Voice'], color: '#1E90FF', use_case: 'A sharp and somewhat intense male voice, suitable for dramatic readings or characters with an edge.' },
    
    // GACRUX UPDATED TO HORROR
    { conceptualName: 'Gacrux (API Standard)', apiName: 'Gacrux', gender: 'Female', category: 'Horror Story', language: 'English', tones: ['Horror Story', 'Authoritative', 'Formal', 'Documentary', 'Fantasy Epic'], color: '#FF69B4', use_case: 'A commanding and deep female voice, perfect for horror, authoritative roles, epic sagas, and formal narration.' },
    
    { conceptualName: 'Iapetus (API Standard)', apiName: 'Iapetus', gender: 'Male', category: 'Ancient Wisdom', language: 'English', tones: ['Ancient Wisdom', 'History', 'Storytelling', 'Biographical'], color: '#1E90FF', use_case: 'A weathered and wise male voice, carrying a sense of history and knowledge. Great for storytelling.' },
    { conceptualName: 'Kore (API Standard)', apiName: 'Kore', gender: 'Female', category: 'Neutral', language: 'English', tones: ['Neutral', 'Formal', 'Corporate Narration', 'Educational'], color: '#FF69B4', use_case: 'The standard female voice from the API. Clear, professional, and highly versatile for any application.' },
    { conceptualName: 'Laomedeia (API Standard)', apiName: 'Laomedeia', gender: 'Female', category: 'Soothing', language: 'English', tones: ['Soothing', 'Gentle', 'Kids Bedtime Story', 'Calm'], color: '#FF69B4', use_case: 'A soft and gentle female voice, ideal for calming content, bedtime stories, and thoughtful narration.' },
    { conceptualName: 'Leda (API Standard)', apiName: 'Leda', gender: 'Female', category: 'Youthful', language: 'English', tones: ['Youthful', 'Cheerful', 'Happy', 'Energetic'], color: '#FF69B4', use_case: 'A bright and youthful female voice from the API, full of energy and optimism.' },
    { conceptualName: 'Orus (API Standard)', apiName: 'Orus', gender: 'Male', category: 'Trustworthy', language: 'English', tones: ['Trustworthy', 'Financial Advice', 'Medical Narration', 'Formal'], color: '#1E90FF', use_case: 'A mature and reassuring male voice, conveying trust and expertise. Excellent for financial or medical content.' },
    { conceptualName: 'Pulcherrima (API Standard)', apiName: 'Pulcherrima', gender: 'Female', category: 'Calm', language: 'English', tones: ['Calm', 'Soothing', 'Guided Meditation', 'Sleep Story'], color: '#FF69B4', use_case: 'A calm and soothing female voice, perfect for relaxation, meditation, and gentle storytelling.' },
    { conceptualName: 'Puck (API Standard)', apiName: 'Puck', gender: 'Male', category: 'Deep', language: 'English', tones: ['Deep', 'Resonant', 'Documentary', 'Movie Trailer', 'Authoritative'], color: '#1E90FF', use_case: 'The standard deep, resonant male voice from the API. Perfect for serious documentaries and trailers.' },
    { conceptualName: 'Rasalgethi (API Standard)', apiName: 'Rasalgethi', gender: 'Male', category: 'Character Voice', language: 'English', tones: ['Character Voice', 'Ancient Wisdom', 'Old', 'Storytelling'], color: '#1E90FF', use_case: 'An older, gravelly male voice, full of character. Perfect for wise old mentors or historical figures.' },
    { conceptualName: 'Sadachbia (API Standard)', apiName: 'Sadachbia', gender: 'Male', category: 'Neutral', language: 'English', tones: ['Neutral', 'Informative', 'E-Learning Module', 'Fact'], color: '#1E90FF', use_case: 'A neutral, mid-range male voice. A solid choice for clear and direct narration.' },
    { conceptualName: 'Sadaltager (API Standard)', apiName: 'Sadaltager', gender: 'Male', category: 'Friendly', language: 'English', tones: ['Friendly', 'Conversational', 'Cheerful', 'Product Demo'], color: '#1E90FF', use_case: 'A bright and friendly male voice, great for commercials and engaging, conversational content.' },
    { conceptualName: 'Schedar (API Standard)', apiName: 'Schedar', gender: 'Male', category: 'Character Voice', language: 'English', tones: ['Character Voice', 'Villainous', 'Horror Story', 'Deep', 'Angry'], color: '#1E90FF', use_case: 'A deep and villainous male voice, perfect for dramatic characters, antagonists, or horror stories.' },
    { conceptualName: 'Sulafat (API Standard)', apiName: 'Sulafat', gender: 'Female', category: 'Caring', language: 'English', tones: ['Caring', 'Empathetic', 'Soothing', 'Gentle'], color: '#FF69B4', use_case: 'A warm and caring female voice, ideal for empathetic and reassuring messages.' },
    { conceptualName: 'Umbriel (API Standard)', apiName: 'Umbriel', gender: 'Male', category: 'Deep', language: 'English', tones: ['Deep', 'Formal', 'Corporate Narration', 'Neutral'], color: '#1E90FF', use_case: 'A standard, deep male voice suitable for a wide range of serious and professional applications.' },
    { conceptualName: 'Vindemiatrix (API Standard)', apiName: 'Vindemiatrix', gender: 'Female', category: 'Professional', language: 'English', tones: ['Professional', 'Articulate', 'Tech Review', 'Scientific Narration'], color: '#FF69B4', use_case: 'A sharp, professional female voice with a clear, articulate delivery. Great for technical narration.' },
    { conceptualName: 'Zephyr (API Standard)', apiName: 'Zephyr', gender: 'Female', category: 'Youthful', language: 'English', tones: ['Youthful', 'Energetic', 'Cheerful', 'Conversational'], color: '#FF69B4', use_case: 'The standard youthful and energetic female voice from the API. Versatile for fun and lively content.' },
    { conceptualName: 'Zubenelgenubi (API Standard)', apiName: 'Zubenelgenubi', gender: 'Male', category: 'Character Voice', language: 'English', tones: ['Character Voice', 'Gritty', 'Crime Story', 'Odd Story'], color: '#1E90FF', use_case: 'A unique, slightly raspy male voice, excellent for distinctive characters and gritty narration.' },
];

// --- MODEL LISTS MOVED FROM config-panel.tsx ---

// FIX: Add missing OPENROUTER_SPECIAL_MODELS export
// These models require a specific array format for content even in text-only requests.
export const OPENROUTER_SPECIAL_MODELS = [
    "nvidia/nemotron-nano-12b-v2-vl:free",
    "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
    "qwen/qwen3-vl-235b-a22b-thinking",
    "allenai/molmo-2-8b",
    "mistralai/mistral-small-3.1-24b-instruct",
    "google/gemma-3-27b-it",
    "google/gemma-4-31b-it:free",
    "qwen/qwen3.8-27b:free",
    "openai/gpt-4o",
    "anthropic/claude-3.5-sonnet",
    "google/gemini-1.5-pro",
    "mistralai/mistral-nemo"
];

export const visualAnalysisModels = [
    { id: "openrouter/free", label: "OpenRouter Auto-Routing (Free)", appFunction: "Dynamic Vision Router", details: "[অটো রাউটিং] এটি সিলেক্ট করলে ওপেন-রাউটার ভিশন/ইমেজ অ্যানালাইসিসের জন্য বেস্ট ফ্রি মাল্টিমডাল মডেলটি বেছে নিয়ে কাজ করবে।" },
    { id: "google/gemma-4-31b-it:free", label: "Google: Gemma 4 31B (Free)", appFunction: "Visual Storyboard Generation, Deep Image Analysis", details: "[প্যারামিটার: 31B | কনটেক্সট: 262K] গুগলের লেটেস্ট মাল্টিমোডাল মডেল। স্ক্রিনশট ও ডেসক্রিপশন অনুযায়ী এটি টেক্সট এবং ইমেজ দুটোই সাপোর্ট করে। ২ লাখেরও বেশি মেমরি থাকায় বড় ভিডিও অ্যানালাইসিস এবং লজিক্যাল প্রম্পট তৈরির জন্য এটি খুবই শক্তিশালী একটি ফ্রি অপশন।" },
    { id: "qwen/qwen3.8-27b:free", label: "Qwen: Qwen3.8 27B (Free)", appFunction: "Vision-Language & Multimodal Reasoning", details: "[প্যারামিটার: 27B | কনটেক্সট: 262K] এটি একটি শক্তিশালী ডেন্স মাল্টিমোডাল মডেল যা উন্নত ফ্রেম অ্যানালাইসিস এবং লজিক্যাল প্রম্পট তৈরিতে কার্যকর।" },
    { id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", label: "NVIDIA: Nemotron 3 Nano Omni (Free)", appFunction: "Advanced Frame Analysis, Reasoning", details: "[প্যারামিটার: 30B | কনটেক্সট: 256K] এটি মাল্টিমোডাল রিজনিং মডেল যা একই সাথে অত্যন্ত ফাস্ট এবং বিশাল মেমোরি সাপোর্ট করে।" },
    { id: "nvidia/nemotron-nano-12b-v2-vl:free", label: "NVIDIA: Nemotron Nano 12B 2 VL (Free)", appFunction: "Video Remake, Extract Script & Styles, Generate Detailed Prompts", details: "[প্যারামিটার: 12B | কনটেক্সট: 128K] এটি ভিডিও এবং ডকুমেন্ট অ্যানালাইসিসের জন্য স্পেশালিস্ট। এর বিশাল ১২৮কে মেমোরি অনেকগুলো ফ্রেম একসাথে মনে রাখতে পারে। এটি অপটিক্যাল ক্যারেক্টার রেকগনিশন (OCR) এবং চার্ট বোঝার জন্য বিশেষভাবে অপ্টিমাইজড।" },
    { id: "allenai/molmo-2-8b", label: "AllenAI: Molmo2 8B", appFunction: "Video Remake, Scene-by-Scene Analysis, Generate Detailed Prompts", details: "[প্যারামিটার: 8B | কনটেক্সট: ~37K] এটি Qwen3-8B এর উপর ভিত্তি করে তৈরি এবং ভিশন ব্যাকবোন হিসেবে SigLIP 2 ব্যবহার করে। ছোট ভিডিও, গণনা (Counting) এবং ক্যাপশনিং-এর ক্ষেত্রে এটি অন্যান্য ওপেন মডেলের চেয়ে ভালো পারফর্ম করে।" },
    { id: "mistralai/mistral-small-3.1-24b-instruct", label: "Mistral: Small 3.1 24B", appFunction: "Logical Scene Understanding", details: "[প্যারামিটার: 24B | কনটেক্সট: 128K] ২৪ বিলিয়ন প্যারামিটারের এই মডেলটি ভিশন এবং লজিক্যাল রিজনিংয়ের জন্য খুব শক্তিশালী। এটি জটিল ইমেজ ডকুমেন্ট এবং ম্যাথমেটিক্যাল রিজনিংয়ের জন্য ভালো কাজ করে।" },
    { id: "google/gemma-3-27b-it", label: "Google: Gemma 3 27B", appFunction: "Visual Storyboard Generation, Multilingual Scene Description, Bangla Output", details: "[প্যারামিটার: 27B | কনটেক্সট: 128K] গুগলের লেটেস্ট এবং এই সিরিজের সবচেয়ে শক্তিশালী ওপেন সোর্স মডেল। এটি ১৪০টিরও বেশি ভাষা বোঝে। উন্নত গণিত, রিজনিং এবং ফাংশন কলিংয়ের সক্ষমতা রয়েছে। এটি ভিশন-ল্যাঙ্গুয়েজ ইনপুট এবং স্ট্রাকচারড আউটপুট (যেমন JSON) দিতে পারে।" },
];

export const storyModels = [
    { id: "nvidia/nemotron-3-ultra-550b-a55b:free", label: "NVIDIA: Nemotron 3 Ultra 550B (Free)", appFunction: "Advanced Story, Script & Prompt Generation", details: "[প্যারামিটার: 550B | কনটেক্সট: 1M] ৫৫০ বিলিয়ন প্যারামিটারের এই দানবীয় মডেলটি যেকোনো বড় স্ক্রিপ্ট, প্রম্পট জেনারেশন বা লজিক্যাল কাজের জন্য দুর্দান্ত ফাস্ট এবং চমৎকার রেজাল্ট দেয়।" },
    { id: "google/gemma-4-26b-a4b-it:free", label: "Google: Gemma 4 26B (Free)", appFunction: "Story & Prompt Generation, Fast Translation", details: "[প্যারামিটার: 26B (MoE)] গুগলের এই মডেলটি স্টোরি এবং প্রম্পট জেনারেশনের জন্য দারুণ পারফর্ম করে। পাশাপাশি এটি অত্যন্ত দ্রুত কাজ করতে সক্ষম।" },
    { id: "openrouter/free", label: "OpenRouter Auto-Routing (Free)", appFunction: "Dynamic Free Router", details: "[অটো রাউটিং] এটি সিলেক্ট করলে ওপেন-রাউটার রিকোয়েস্টের ধরন অনুযায়ী নিজে থেকে সবচেয়ে বেস্ট এভেইলেবল ফ্রি মডেলটি বেছে নিয়ে কাজ করবে।" },
    { id: "nvidia/nemotron-3-super-120b-a12b:free", label: "NVIDIA: Nemotron 3 Super 120B (Free)", appFunction: "Advanced Reasoning, Complex Multi-agent Tasks, Fast Story Generation", details: "[প্যারামিটার: 120B (MoE) | কনটেক্সট: 262K] এটি অত্যন্ত শক্তিশালী একটি মডেল যা 1M টোকেন কনটেক্সট উইন্ডো सपोर्ट করে। এটি বিশাল ডকুমেন্ট বা স্ক্রিপ্ট নিয়ে লজিক্যাল রিজনিং এবং প্লট প্ল্যানিংয়ের জন্য খুব ভালো।" },
    { id: "google/gemma-4-31b-it:free", label: "Google: Gemma 4 31B (Free)", appFunction: "Advanced Reasoning, Multilingual Storytelling", details: "[প্যারামিটার: 31B | কনটেক্সট: 262K] গুগলের এই লেটেস্ট ফ্রি মডেলটিতে 262K কনটেক্সট উইন্ডো এবং থিংকিং/রিজনিং মোড রয়েছে। অনেক বড় স্ক্রিপ্ট এনালাইজ করে কনসিস্টেন্ট প্রম্পট বা গল্প লিখতে এটি দারুণ কাজ করবে।" },
    { id: "tencent/hy3-preview:free", label: "Tencent: Hy3 Preview (Free)", appFunction: "High-efficiency MoE, Reasoning, Coding", details: "[প্যারামিটার: High (MoE) | কনটেক্সট: 262K] এটি টেনসেন্ট-এর অত্যন্ত শক্তিশালী একটি মডেল যা কনফিগারযোগ্য রিজনিং এবং জটিল কোডিং বা স্ট্রাকচারড কাজের জন্য বেশ ফাস্ট।" },
    { id: "qwen/qwen3-next-80b-a3b-instruct:free", label: "Qwen: Qwen3 Next 80B A3B Instruct (Free)", appFunction: "Advanced Story Structuring, Long Context Analysis", details: "[প্যারামিটার: 80B | কনটেক্সট: 262K] এর ২৬২কে (262K) বিশাল কনটেক্সট উইন্ডো আছে। যদি আপনার স্ক্রিপ্ট অনেক বড় হয় এবং সেটা এনালাইজ করে নতুন কিছু লিখতে হয়, তবে এটি ব্যবহার করবেন।" },
    { id: "meta-llama/llama-3.3-70b-instruct:free", label: "Meta: Llama 3.3 70B Instruct (Free)", appFunction: "Balanced Story Generation, Fast Creative Rephrasing", details: "[প্যারামিটার: 70B | কনটেক্সট: 131K] এটি 405B এর চেয়ে Fast (দ্রুত) কিন্তু সৃজনশীলতায় খুব কাছাকাছি। যদি 405B স্লো কাজ করে, তবে ব্যালেন্সড ক্রিয়েটিভ আউটপুটের জন্য এটি সেরা ব্যাকআপ অপশন।" },
    { id: "openai/gpt-oss-20b:free", label: "OpenAI: gpt-oss-20b (Free)", appFunction: "Basic Writing, Legacy Tasks", details: "[প্যারামিটার: 21B | কনটেক্সট: 131K] ওপেনএআই-এর রিলিজ করা ওপেন ওয়েট মডেল (MoE)। এটি ফাস্ট এবং সাধারণ লেখার জন্য বেশ কার্যকর।" },
    { id: "nousresearch/hermes-3-llama-3.1-405b:free", label: "Nous: Hermes 3 405B Instruct (Free)", appFunction: "Idea to Story, Creative Script Writing, Uncensored Creativity", details: "[প্যারামিটার: 405B | কনটেক্সট: 131K] শূন্য থেকে গল্প বানানোর জন্য এটি Llama-র চেয়ে বেশি শক্তিশালী কারণ এটি আনসেন্সরড এবং অনেক বেশি Creative (সৃজনশীল)। ফিকশন, ড্রামা বা ইমোশনাল স্ক্রিপ্ট লেখার জন্য এটি সেরা চয়েস।" },
    { id: "meta-llama/llama-3.1-405b-instruct", label: "Meta: Llama 3.1 405B Instruct", appFunction: "Generate New Story - Professional, High Logic Rephrasing", details: "[প্যারামিটার: 405B | কনটেক্সট: 131K] এটি ওপেন সোর্সের সবচেয়ে বুদ্ধিমান মডেল। যদি আপনি খুব গোছানো, প্রফেশনাল এবং লজিক্যাল গল্প চান তবে এটি ব্যবহার করবেন। প্যারাফ্রেজিং-এর সময় এটি মূল ভাব বজায় রেখে খুব স্মার্টলি বাক্য পরিবর্তন করতে পারে।" },
    { id: "qwen/qwen3-coder", label: "Qwen: Qwen3 Coder 480B A35B", appFunction: "Logical Structuring, Complex Plot Analysis", details: "[প্যারামিটার: 480B | কনটেক্সট: 262K] যদিও এটি কোডিং মডেল, কিন্তু এর লজিক এবং রিজনিং ক্ষমতা ৪৫০ বিলিয়নের উপরে। ডিটেকটিভ স্টোরি বা জটিল প্লট সাজানোর জন্য এটি ব্যবহার করতে পারেন।" },
    { id: "upstage/solar-pro-3", label: "Upstage: Solar Pro 3", appFunction: "Powerful MoE Storytelling, Advanced Reasoning", details: "[প্যারামিটার: High (MoE) | কনটেক্সট: 128K] এটি একটি অত্যন্ত শক্তিশালী Mixture-of-Experts মডেল। এর লজিক এবং লেখার স্টাইল খুবই উন্নত। অ্যাপের \"Refine Story\" বা জটিল স্ক্রিপ্ট লেখার জন্য এটি চমৎকার বিকল্প।" },
    { id: "openai/gpt-oss-120b", label: "OpenAI: gpt-oss-120b", appFunction: "General Purpose Writing, Legacy Support", details: "[প্যারামিটার: 120B | কনটেক্সট: 131K] ওপেনএআই-এর রিলিজ করা ওপেন ওয়েট মডেল। সাধারণ মানের গল্প বা ব্লগের জন্য ব্যবহার করা যেতে পারে।" },
    { id: "tngtech/tng-r1t-chimera", label: "TNG: R1T Chimera", appFunction: "Creative Roleplay - Backup", details: "[প্যারামিটার: High | কনটেক্সট: 164K] এটিও চিমেরা সিরিজের আরেকটি ভেরিয়েন্ট। রোল-প্লে এবং ক্রিয়েটিভ লেখার জন্য ব্যবহারযোগ্য।" },
    { id: "moonshotai/kimi-k2", label: "MoonshotAI: Kimi K2 0711", appFunction: "Creative Paraphrasing, Long Script Refinement", details: "[প্যারামিটার: 1T (MoE) | কনটেক্সট: 33K] ১ ট্রিলিয়ন প্যারামিটারের এই মডেলটি প্যারাফ্রেজিং-এর সময় রোবোটিক ভাব দূর করে মানুষের মতো ন্যাচারাল ফ্লো আনতে পারে।" },
    { id: "nvidia/nemotron-3-nano-30b-a3b:free", label: "NVIDIA: Nemotron 3 Nano 30B A3B (Free)", appFunction: "Efficient Long Script Processing", details: "[প্যারামিটার: 30B | কনটেক্সট: 256K] এটি সাইজে ছোট হলেও এর মেমোরি অনেক বেশি (256K)। বড় ডকুমেন্ট প্রসেসিং-এর জন্য ভালো।" },
    { id: "arcee-ai/trinity-large-thinking:free", label: "Arcee AI: Trinity Large Thinking (Free)", appFunction: "Advanced Reasoning, Agentic Tasks", details: "[প্যারামিটার: 19.3B | কনটেক্সট: 262K] শক্তিশালী ওপেন সোর্স রিজনিং মডেল যা এজেন্টিক ওয়ার্কফ্লো এবং জটিল লজিক্যাল কাজের জন্য খুব উপযোগী।" },
    { id: "deepseek/deepseek-v4-flash:free", label: "DeepSeek: DeepSeek V4 Flash (Free)", appFunction: "Fast Inference, High Throughput", details: "[প্যারামিটার: 284B | কনটেক্সট: 1M] অত্যন্ত দ্রুত গতির এবং হাই থ্রুপুট মডেল। এটি বিশাল ১ মিলিয়ন কনটেক্সট সাপোর্ট করে এবং লজিক্যাল এনালাইসিসের জন্য দুর্দান্ত।" },
    { id: "cognitivecomputations/dolphin-mistral-24b-venice-edition", label: "Venice: Uncensored", appFunction: "Uncensored Story Writing, Roleplay", details: "[প্যারামিটার: 24B | কনটেক্সট: 33K] এটি Mistral এর একটি আনসেন্সরড ভার্সন। যদি ইউজার এমন কোনো গল্প লিখতে চায় যেখানে কোনো রেস্ট্রিকশন থাকবে না, তবে এটি কাজে লাগবে।" },
];

export const translationModels = [
    { id: "nvidia/nemotron-3-ultra-550b-a55b:free", label: "NVIDIA: Nemotron 3 Ultra 550B (Free)", appFunction: "High Quality Fast Translation", details: "[প্যারামিটার: 550B | কনটেক্সট: 1M] বিশাল সাইজের কারণে এটি অত্যন্ত নিখুঁত এবং দ্রুত অনুবাদ করতে পারে।" },
    { id: "google/gemma-4-26b-a4b-it:free", label: "Google: Gemma 4 26B (Free)", appFunction: "Fast Translation & Rephrasing", details: "[প্যারামিটার: 26B (MoE)] গুগলের এই মডেলটি ট্রান্সলেশন বা রি-রাইট করার জন্য বেশ ফাস্ট এবং নির্ভরযোগ্য।" },
    { id: "openrouter/free", label: "OpenRouter Auto-Routing (Free)", appFunction: "Dynamic Free Router", details: "[অটো রাউটিং] এটি সিলেক্ট করলে ওপেন-রাউটার ট্রান্সলেশনের জন্য বেস্ট ফ্রি মডেলটি বেছে নেবে।" },
    { id: "z-ai/glm-4.5-air:free", label: "Z.AI: GLM 4.5 Air (Free)", appFunction: "High Quality Translation - Asian Languages, Balanced Rephrasing", details: "[প্যারামিটার: 29B | কনটেক্সট: 131K] এটি এশিয়ান ভাষা এবং ইংরেজির মধ্যে অনুবাদের জন্য খুবই শক্তিশালী। এটি \"Thinking Mode\" ব্যবহার করে লজিক্যাল অনুবাদ করতে পারে।" },
    { id: "nvidia/nemotron-nano-9b-v2", label: "NVIDIA: Nemotron Nano 9B V2", appFunction: "Mid-range Translation, Document Processing", details: "[প্যারামিটার: 9B | কনটেক্সট: 128K] এনভিডিয়ার এই মডেলটি ডকুমেন্ট বা অফিশিয়াল টেক্সট অনুবাদের জন্য বেশ ভালো।" },
    { id: "qwen/qwen3-4b", label: "Qwen: Qwen3 4B", appFunction: "Fast Translation, Dense Logic", details: "[প্যারামিটার: 4B | কনটেক্সট: 41K] Qwen সিরিজের নতুন মডেল। এটি ছোট হলেও অত্যন্ত ডেন্স এবং স্মার্ট। অনুবাদের জন্য এটি বেশ Fast (দ্রুত)।" },
    { id: "meta-llama/llama-3.2-3b-instruct", label: "Meta: Llama 3.2 3B Instruct", appFunction: "Fastest English Rephrasing - Fast", details: "[প্যারামিটার: 3B | কনটেক্সট: 131K] এটি তালিকার Fastest (সবচেয়ে দ্রুত) মডেল। শুধুমাত্র ইংরেজি ছোটখাটো রি-রাইট বা গ্রামার চেকের জন্য এটি সেরা।" },
    { id: "google/gemma-3n-e4b-it", label: "Google: Gemma 3n 4B", appFunction: "Fast Mobile Optimized Translation - Bangla Supported", details: "[প্যারামিটার: 4B | কনটেক্সট: 8K] এটি গুগলের 'n' (Nano) সিরিজের মডেল। ১৪০+ ভাষা সাপোর্ট করে এবং লো-রিসোর্স ডিভাইসে খুব Fast (দ্রুত) কাজ করে।" },
    { id: "google/gemma-3n-e2b-it", label: "Google: Gemma 3n 2B", appFunction: "Super Fast Translation, Basic Chat", details: "[প্যারামিটার: 2B | কনটেক্সট: 8K] লিস্টের সবচেয়ে ছোট এবং Super Fast (সুপার ফাস্ট) মডেল। খুব সাধারণ মানের দ্রুত অনুবাদ বা টেস্ট পারপাসে এটি ব্যবহার করা যেতে পারে।" },
    { id: "liquid/lfm-2.5-1.2b-instruct", label: "LiquidAI: LFM2.5-1.2B-Instruct", appFunction: "Ultra-Lightweight Tasks", details: "[প্যারামিটার: 1.2B | কনটেক্সট: 32K] অত্যন্ত হালকা মডেল। শুধুমাত্র খুব সাধারণ এবং ছোট টেক্সট প্রসেসিংয়ের জন্য।" },
    { id: "liquid/lfm-2.5-1.2b-thinking", label: "LiquidAI: LFM2.5-1.2B-Thinking", appFunction: "Experimental Reasoning", details: "[প্যারামিটার: 1.2B | কনটেক্সট: 32K] ছোট সাইজের মধ্যে রিজনিং বা লজিক টেস্ট করার জন্য এটি ব্যবহার করা যায়।" },
];

export const paidVisionModels = [
    { id: "qwen/qwen3-vl-235b-a22b-thinking", label: "Qwen: Qwen3 VL 235B (Thinking)", appFunction: "Advanced Visual Analysis, Thinking Mode", details: "[Paid Model] [প্যারামিটার: 235B | কনটেক্সট: 128K] Qwen সিরিজের শক্তিশালী ভিশন মডেল। এটি ইমেজ অ্যানালাইসিসের সময় 'Thinking' মুড ব্যবহার করে জটিল দৃশ্য বুঝতে পারে।" },
    { id: "openai/gpt-4o", label: "OpenAI: GPT-4o", appFunction: "Vision", details: "Paid Model" },
    { id: "anthropic/claude-3.5-sonnet", label: "Anthropic: Claude 3.5 Sonnet", appFunction: "Vision", details: "Paid Model" },
    { id: "google/gemini-1.5-pro", label: "Google: Gemini 1.5 Pro", appFunction: "Vision", details: "Paid Model" },
    { id: "mistralai/mistral-nemo", label: "Mistral: Nemo", appFunction: "Vision", details: "Paid Model" }
];
export const paidTextModels = [ 
    { id: "meta-llama/llama-3.1-70b-instruct", label: "Meta: Llama 3.1 70B Instruct", appFunction: "Text", details: "Paid Model" },
    { id: "arcee-ai/trinity-large-preview", label: "Arcee AI: Trinity Large Preview", appFunction: "Pure Storytelling, Idea to Story", details: "Paid Model" },
    { id: "arcee-ai/trinity-mini", label: "Arcee AI: Trinity Mini", appFunction: "Lightweight Storytelling, Quick Ideas", details: "Paid Model" },
    { id: "tngtech/deepseek-r1t2-chimera", label: "TNG: DeepSeek R1T2 Chimera", appFunction: "Text", details: "Paid Model [প্যারামিটার: 671B]" },
    { id: "deepseek/deepseek-r1-0528", label: "DeepSeek: R1 0528", appFunction: "Text", details: "Paid Model [প্যারামিটার: 671B]" },
    { id: "tngtech/deepseek-r1t-chimera", label: "TNG: DeepSeek R1T Chimera", appFunction: "Text", details: "Paid Model" },
];

export type ModelItem = { id: string; label: string; appFunction: string; details: string; };
export type HeaderItem = { isHeader: true; label: string; };
export const allTextVisionModels: (ModelItem | HeaderItem)[] = [
    { isHeader: true, label: "🎬 Visual Analysis Models" }, ...visualAnalysisModels,
    { isHeader: true, label: "📝 Story Generation, Creative Writing & Refinement" }, ...storyModels,
    { isHeader: true, label: "🌐 Translation & Multilingual" }, ...translationModels,
    { isHeader: true, label: "💎 Paid Vision Models" }, ...paidVisionModels,
    { isHeader: true, label: "💎 Paid Text Models" }, ...paidTextModels
];

export const openRouterFreeImageModels: {value: string, label: string}[] = [
    { value: "pollinations", label: "Pollinations AI (Totally Free, No Key Required)" }
];

export const openRouterPaidImageModels = [
    // --- Formerly 'Free', now correctly labeled as Paid for output ---
    { value: "black-forest-labs/flux.2-max", label: "FLUX.2 Max (Paid) [Top-Tier Quality]" },
    { value: "black-forest-labs/flux.2-pro", label: "FLUX.2 Pro (Paid) [High-End Generation & Editing]" },
    { value: "sourceful/riverflow-v2-max-preview", label: "Riverflow V2 Max (Paid) [Powerful Text-to-Image]" },
    { value: "black-forest-labs/flux.2-klein-4b", label: "FLUX.2 Klein 4B (Paid) [Fast & Cost-Effective]" },
    { value: "bytedance-seed/seedream-4.5", label: "Seedream 4.5 (Paid) [Editing & Consistency]" },
    { value: "playgroundai/playground-v2.5", label: "Playground v2.5 (Paid) [Aesthetic Images]" },
    // --- Original Paid Models ---
    { value: "stabilityai/stable-diffusion-3-medium", label: "Stability AI: SD3 Medium (Paid)" },
    { value: "openai/dall-e-3", label: "OpenAI: DALL-E 3 (Paid)" },
    { value: "ideogram/ideogram-v2", label: "Ideogram v2 (Paid)" },
    { value: "google/imagen-3", label: "Google: Imagen 3 (Paid)" },
];